build:
    environment:
        php:
            version: 8.0
    dependencies:
        before:
            - 'composer install'
    tests:
        before:
            -
                command: vendor/bin/phpunit --verbose -c ./phpunit.xml.dist
                coverage:
                    file: clover.xml
                    format: clover