build:
    environment:
        php:
            version: 7.1
    dependencies:
            before:
              - composer install
    tests:
        override:
            -
                command: phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover