build:
    environment:
        php:
            version: 7.1
    dependencies:
            before:
              - composer install
    tests:
        override:
            -
                command: phpunit --verbose -c ./phpunit.xml.dist
                coverage:
                    file: clover.xml
                    format: php-clover